[versions]
versionCode = "115"
versionName = "1.6.0"

compileSdk = "34"
minSdk = "24"
targetSdk = "34"
kotlinLanguage = "1.9"
composeCompiler = "1.5.1"

gradle = "8.1.4"
kotlin = "1.9.0"
versionsChecker = "0.47.0"

hilt = "2.48.1"
room = "2.6.0"
retrofit = "2.9.0"
moshi = "1.15.0"
okhttp = "4.12.0"
exoplayer = "1.1.1"
composeLifecycle = "2.6.2"

test = "1.5.0"
mockk = "1.13.8"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.0-1.0.12" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.0" }
versionsChecker = { id = "com.github.ben-manes.versions", version.ref = "versionsChecker" }


[libraries]
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version = "2.8.1" }
dataStore-base = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }
kotlin-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version = "1.7.3" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

retrofit-base = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-test = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }

moshi-kotlin-base = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

okhttp-base = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-test = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

media3-exoplayer-base = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayer" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "exoplayer" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2023.10.01" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
compose-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "composeLifecycle" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.8.0" }
compose-navigation-base = { module = "androidx.navigation:navigation-compose", version = "2.7.5" }
compose-navigation-hilt = { module = "androidx.hilt:hilt-navigation-compose", version = "1.1.0" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-extended", version = "1.5.4" }
coil-compose = { module = "io.coil-kt:coil-compose", version = "2.5.0" }

accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version = "0.32.0" }

lottie = { module = "com.airbnb.android:lottie-compose", version = "6.1.0" }
splashScreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }

junit = { module = "junit:junit", version = "4.13.2" }
junitExt = { module = "androidx.test.ext:junit", version = "1.1.5" }

test-core = { module = "androidx.test:core", version.ref = "test" }
test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "test" }
test-runner = { module = "androidx.test:runner", version = "1.5.2" }
test-orchestrator = { module = "androidx.test:orchestrator", version = "1.4.2" }


mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }

coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.7.3" }



