[versions]
versionCode = "110"
versionName = "1.1.0"

compileSdk = "33"
minSdk = "24"
targetSdk = "33"
kotlinLanguage = "1.9"
composeCompiler = "1.5.1"

gradle = "8.1.0"
kotlin = "1.9.0"
versionsChecker = "0.47.0"

hilt = "2.47"
room = "2.5.2"
retrofit = "2.9.0"
moshi = "1.15.0"
okhttp = "4.11.0"
exoplayer = "1.1.0"
composeLifecycle = "2.6.1"
accompanist = "0.30.1"


[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.0-1.0.12" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.0" }
versionsChecker = { id = "com.github.ben-manes.versions", version.ref = "versionsChecker" }


[libraries]
plugin-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-versionsChecker = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsChecker" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.10.1" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version = "2.8.1" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

retrofit-base = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

moshi-kotlin-base = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

okhttp-base = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

media3-exoplayer-base = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayer" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2023.06.01" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
compose-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "composeLifecycle" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.7.2" }
compose-navigation-base = { module = "androidx.navigation:navigation-compose", version = "2.6.0" }
compose-navigation-hilt = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
coil-compose = { module = "io.coil-kt:coil-compose", version = "2.4.0" }

accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

junit-base = { module = "junit:junit", version = "4.13.2" }
junit-ext = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }


