[versions]

versionCode = "118"
versionName = "1.8.0"

compileSdk = "34"
minSdk = "26"
targetSdk = "34"

javaVersion = "17"
kotlinLanguage = "1.9"
composeCompiler = "1.5.5"

gradle = "8.2.0"
kotlin = "1.9.20"
versionsChecker = "0.47.0"

ksp = "1.9.20-1.0.14"
hilt = "2.48.1"
room = "2.6.1"
retrofit = "2.9.0"
moshi = "1.15.0"
okhttp = "4.12.0"
exoplayer = "1.2.0"
composeLifecycle = "2.6.2"
test = "1.5.0"
mockk = "1.13.8"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
accompanist = "0.32.0"

[plugins]

androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.0" }
versionsChecker = { id = "com.github.ben-manes.versions", version.ref = "versionsChecker" }

radiostations-android-application = { id = "radiostations.android.application", version = "unspecified" }
radiostations-android-library = { id = "radiostations.android.library", version = "unspecified" }
radiostations-android-feature = { id = "radiostations.android.feature", version = "unspecified" }
radiostations-android-hilt = { id = "radiostations.android.hilt", version = "unspecified" }
radiostations-android-application-compose = { id = "radiostations.android.application.compose", version = "unspecified" }
radiostations-android-library-compose = { id = "radiostations.android.library.compose", version = "unspecified" }
radiostations-android-room = { id = "radiostations.android.room", version = "unspecified" }


[libraries]

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kspGradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version = "2.9.0" }
dataStore-base = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }
kotlin-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version = "1.7.3" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

retrofit-base = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-test = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }

moshi-kotlin-base = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

okhttp-base = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-test = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

media3-exoplayer-base = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayer" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "exoplayer" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2023.10.01" }

compose-animation = { module = "androidx.compose.animation:animation" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }

compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
compose-lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "composeLifecycle" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.8.1" }
compose-navigation-base = { module = "androidx.navigation:navigation-compose", version = "2.7.5" }
compose-navigation-hilt = { module = "androidx.hilt:hilt-navigation-compose", version = "1.1.0" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-extended", version = "1.5.4" }

accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

coil-compose = { module = "io.coil-kt:coil-compose", version = "2.5.0" }
lottie = { module = "com.airbnb.android:lottie-compose", version = "6.1.0" }
splashScreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }

junit = { module = "junit:junit", version = "4.13.2" }
junitExt = { module = "androidx.test.ext:junit", version = "1.1.5" }

test-core = { module = "androidx.test:core", version.ref = "test" }
test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "test" }
test-runner = { module = "androidx.test:runner", version = "1.5.2" }
test-orchestrator = { module = "androidx.test:orchestrator", version = "1.4.2" }

mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }

coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.7.3" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }