name: Github Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create keystrore.properties
        run: touch keystore.properties

      - name: Decode keystore file
        run: echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > key_radiostations.jks

      - name: Add keystore data to keystore.properties
        run: echo "${{ secrets.KEYSTORE_DATA }}" >> keystore.properties

      - name: Build release
        run: ./gradlew assembleRelease

      - name: Extract versionName
        id: extract_version
        run: echo ::set-output name=version::$(awk -F' = ' '/versionName/ {gsub(/"/, "", $2); print $2}' libs.versions.toml)

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: app/release/app-release.apk
          title: ${{ steps.extract_version.outputs.version }}
          tag_name: v${{ steps.extract_version.outputs.version }}
          body: "For demonstration"